package dev.jobflow.domain;
import com.fasterxml.jackson.databind.JsonNode; import jakarta.persistence.*; import org.hibernate.annotations.JdbcTypeCode; import org.hibernate.type.SqlTypes; import java.time.Instant; import java.util.UUID;
@Entity @Table(name="jobs") public class Job {
 @Id private UUID id; @ManyToOne(fetch=FetchType.LAZY) @JoinColumn(name="owner_id",nullable=false) private AppUser owner; @Enumerated(EnumType.STRING) @Column(nullable=false) private JobType type; @JdbcTypeCode(SqlTypes.JSON) @Column(nullable=false,columnDefinition="jsonb") private JsonNode payload; @Enumerated(EnumType.STRING) @Column(nullable=false) private JobPriority priority; @Enumerated(EnumType.STRING) @Column(nullable=false) private JobStatus status; @Column(name="available_at",nullable=false) private Instant availableAt; @Column(name="lease_expires_at") private Instant leaseExpiresAt; @Column(name="attempt_count",nullable=false) private int attemptCount; @Column(name="max_attempts",nullable=false) private int maxAttempts; @JdbcTypeCode(SqlTypes.JSON) @Column(columnDefinition="jsonb") private JsonNode result; @Column(name="error_code") private String errorCode; @Column(name="error_message") private String errorMessage; @Column(name="idempotency_key") private String idempotencyKey; @Column(name="created_at",nullable=false) private Instant createdAt; @Column(name="updated_at",nullable=false) private Instant updatedAt; @Version private long version;
 protected Job(){} public Job(AppUser owner,JobType type,JsonNode payload,JobPriority priority,int maxAttempts,String key){id=UUID.randomUUID();this.owner=owner;this.type=type;this.payload=payload;this.priority=priority;this.maxAttempts=maxAttempts;idempotencyKey=key;status=JobStatus.QUEUED;createdAt=updatedAt=availableAt=Instant.now();}
 public UUID getId(){return id;} public AppUser getOwner(){return owner;} public JobType getType(){return type;} public JsonNode getPayload(){return payload;} public JobPriority getPriority(){return priority;} public JobStatus getStatus(){return status;} public Instant getAvailableAt(){return availableAt;} public Instant getLeaseExpiresAt(){return leaseExpiresAt;} public int getAttemptCount(){return attemptCount;} public int getMaxAttempts(){return maxAttempts;} public JsonNode getResult(){return result;} public String getErrorCode(){return errorCode;} public String getErrorMessage(){return errorMessage;} public String getIdempotencyKey(){return idempotencyKey;} public Instant getCreatedAt(){return createdAt;} public Instant getUpdatedAt(){return updatedAt;}
 public void claim(Instant leaseUntil){JobStateMachine.require(status,JobStatus.PROCESSING);status=JobStatus.PROCESSING;attemptCount++;leaseExpiresAt=leaseUntil;}
 public void complete(JsonNode value){JobStateMachine.require(status,JobStatus.COMPLETED);status=JobStatus.COMPLETED;result=value;leaseExpiresAt=null;errorCode=null;errorMessage=null;}
 public void retry(Instant next,String code,String message){JobStateMachine.require(status,JobStatus.RETRY_WAIT);status=JobStatus.RETRY_WAIT;availableAt=next;leaseExpiresAt=null;errorCode=code;errorMessage=message;}
 public void deadLetter(String code,String message){JobStateMachine.require(status,JobStatus.DEAD_LETTER);status=JobStatus.DEAD_LETTER;leaseExpiresAt=null;errorCode=code;errorMessage=message;}
 public void cancel(){JobStateMachine.require(status,JobStatus.CANCELLED);status=JobStatus.CANCELLED;leaseExpiresAt=null;}
 public void recoverExpired(){if(status!=JobStatus.PROCESSING) throw new IllegalStateException("Only processing jobs can be recovered"); if(attemptCount>=maxAttempts) deadLetter("LEASE_EXPIRED","Worker lease expired after final attempt"); else {status=JobStatus.RETRY_WAIT;availableAt=Instant.now();leaseExpiresAt=null;errorCode="LEASE_EXPIRED";errorMessage="Worker lease expired before completion";}}
 public void replay(){if(status!=JobStatus.DEAD_LETTER) throw new IllegalStateException("Only dead-letter jobs can be replayed");status=JobStatus.QUEUED;attemptCount=0;availableAt=Instant.now();leaseExpiresAt=null;errorCode=null;errorMessage=null;}
}
